/**
 * Kernel and initialization code for the stencil
 *
 * (u[0][0][0][1][0]=((alpha*u[0][0][0][0][0])+(beta*((u[1][0][0][0][0]+(u[-1][0][0][0][0]+u[0][1][0][0][0]))+(u[0][-1][0][0][0]+(u[0][0][1][0][0]+u[0][0][-1][0][0]))))))
 * 
 * Strategy: /home/christen/workspace/Patus-GoogleCode/strategy/simple.stg
 * 
 * This code was generated by Patus on 2011/08/11 16:44:03
 */

#include "omp.h"
#include "xmmintrin.h"
#include "emmintrin.h"
#include <stdint.h>

void laplacian___unroll_p2_20101(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, float alpha, float beta, int x_max, int y_max, int z_max, int chunk)
{
	int _idx0;
	int _idx1;
	int _idx10;
	int _idx11;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx2;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int _idx9;
	int end0;
	int numthds0;
	int p2_embed_blkidx_x;
	int p2_embed_blkidx_x_idxouter;
	int p2_embed_idx_x;
	int p2_embed_idx_x_max;
	int p2_embed_idx_y;
	int p2_embed_idx_y_max;
	int p2_embed_idx_z;
	int p2_embed_idx_z_max;
	int p2_idx_x;
	int p2_idx_y;
	int p2_idx_z;
	int prologueend0;
	__m128 splat0 = _mm_load1_ps(( & alpha));
	__m128 splat1 = _mm_load1_ps(( & beta));
	int start0;
	int stepouter0;
	int tmp_stride_0z;
	int tmpidxc0;
	__m128 u_0_0_minus_1__0_0_0__offs_4_0_0;
	__m128 u_0_0_minus_1__m4_0_0__offs_0_0_0;
	__m128 u_0_0_plus_1__0_0_0__offs_0_0_0;
	__m128 u_0_0_plus_1__4_0_0__offs_4_0_0;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	start0=omp_get_thread_num();
	end0=(((((int)(((2*x_max)-1)/x_max))*((int)y_max))*((int)z_max))-1);
	numthds0=omp_get_num_threads();
	stepouter0=(chunk*numthds0);
	/*
	for p2_embed_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
	*/
	for (p2_embed_blkidx_x_idxouter=(start0*chunk); p2_embed_blkidx_x_idxouter<=end0; p2_embed_blkidx_x_idxouter+=stepouter0)
	{
		/*
		for p2_embed_blkidx_x = p2_embed_blkidx_x_idxouter..min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (p2_embed_blkidx_x=p2_embed_blkidx_x_idxouter; p2_embed_blkidx_x<=min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)); p2_embed_blkidx_x+=1)
		{
			tmp_stride_0z=(((int)(((2*x_max)-1)/x_max))*((int)(y_max/1)));
			p2_embed_idx_z=(p2_embed_blkidx_x/tmp_stride_0z);
			tmpidxc0=(p2_embed_blkidx_x-(p2_embed_idx_z*tmp_stride_0z));
			p2_embed_idx_y=(tmpidxc0/((int)(((2*x_max)-1)/x_max)));
			tmpidxc0-=(p2_embed_idx_y*((int)(((2*x_max)-1)/x_max)));
			p2_embed_idx_x=tmpidxc0;
			p2_embed_idx_x=((p2_embed_idx_x*x_max)+1);
			p2_embed_idx_x_max=min((p2_embed_idx_x+x_max), (x_max+1));
			p2_embed_idx_y=((p2_embed_idx_y*1)+1);
			p2_embed_idx_y_max=min((p2_embed_idx_y+1), (y_max+1));
			p2_embed_idx_z=((p2_embed_idx_z*1)+1);
			p2_embed_idx_z_max=min((p2_embed_idx_z+1), (z_max+1));
			/* Index bounds calculations for iterators in p2_embed[t=t][0] */
			/*
			for POINT p2[t=t][0] of size [1, 1, 1] in p2_embed[t=t][0] + [ min=[0, 0, 0], max=[0, 0, 0] ] parallel 1 <level 1> schedule default { ... }
			*/
			{
				/* Index bounds calculations for iterators in p2[t=t][0] */
				p2_idx_z=p2_embed_idx_z;
				p2_idx_y=p2_embed_idx_y;
				p2_idx_x=p2_embed_idx_x;
				/* _idx0 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
				_idx0=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
				prologueend0=min((p2_embed_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), p2_embed_idx_x_max);
				for (p2_idx_x=p2_embed_idx_x; p2_idx_x<prologueend0; p2_idx_x ++ )
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx12 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx12=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx13 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+1)) */
					_idx13=(_idx12+1);
					/* _idx14 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1)) */
					_idx14=(_idx12-1);
					/* _idx15 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx15=((_idx12+x_max)+2);
					/* _idx16 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx16=((_idx12-x_max)-2);
					/* _idx17 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx17=(((_idx16+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx18 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx18=(((_idx16+((( - x_max)-2)*y_max))-x_max)-2);
					u_0_1[_idx12]=((alpha*u_0_0[_idx12])+(beta*((u_0_0[_idx13]+(u_0_0[_idx14]+u_0_0[_idx15]))+(u_0_0[_idx16]+(u_0_0[_idx17]+u_0_0[_idx18])))));
				}
				for (; p2_idx_x<(p2_embed_idx_x_max-7); p2_idx_x+=8)
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx0 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx0=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx1 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+4)) */
					_idx1=(_idx0+4);
					u_0_0_plus_1__0_0_0__offs_0_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx1]))), 15), 137);
					/* _idx2 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-4)) */
					_idx2=(_idx1-8);
					u_0_0_minus_1__m4_0_0__offs_0_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
					/* _idx3 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx3=((_idx1+x_max)-2);
					/* _idx4 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx4=((_idx2-x_max)+2);
					/* _idx5 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx5=(((_idx4+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx6 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx6=(((_idx4+((( - x_max)-2)*y_max))-x_max)-2);
					( * ((__m128 * )( & u_0_1[_idx0])))=_mm_add_ps(_mm_mul_ps(splat0, ( * ((__m128 * )( & u_0_0[_idx0])))), _mm_mul_ps(splat1, _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0_0__offs_0_0_0, _mm_add_ps(u_0_0_minus_1__m4_0_0__offs_0_0_0, ( * ((__m128 * )( & u_0_0[_idx3]))))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx4]))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx5]))), ( * ((__m128 * )( & u_0_0[_idx6]))))))));
					/* _idx7 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+8)) */
					_idx7=((_idx4+x_max)+10);
					u_0_0_plus_1__4_0_0__offs_4_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), 137);
					u_0_0_minus_1__0_0_0__offs_4_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx1]))), 15), ( * ((__m128 * )( & u_0_0[_idx1]))), 152);
					/* _idx8 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+(p2_idx_x+4)) */
					_idx8=((_idx1+x_max)+2);
					/* _idx9 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+(p2_idx_x+4)) */
					_idx9=(_idx4+4);
					/* _idx10 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+(p2_idx_x+4)) */
					_idx10=(_idx5+4);
					/* _idx11 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+(p2_idx_x+4)) */
					_idx11=(_idx6+4);
					( * ((__m128 * )( & u_0_1[_idx1])))=_mm_add_ps(_mm_mul_ps(splat0, ( * ((__m128 * )( & u_0_0[_idx1])))), _mm_mul_ps(splat1, _mm_add_ps(_mm_add_ps(u_0_0_plus_1__4_0_0__offs_4_0_0, _mm_add_ps(u_0_0_minus_1__0_0_0__offs_4_0_0, ( * ((__m128 * )( & u_0_0[_idx8]))))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx9]))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx10]))), ( * ((__m128 * )( & u_0_0[_idx11]))))))));
				}
				for (; p2_idx_x<p2_embed_idx_x_max; p2_idx_x ++ )
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx12 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx12=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx13 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+1)) */
					_idx13=(_idx12+1);
					/* _idx14 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1)) */
					_idx14=(_idx12-1);
					/* _idx15 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx15=((_idx12+x_max)+2);
					/* _idx16 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx16=((_idx12-x_max)-2);
					/* _idx17 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx17=(((_idx16+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx18 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx18=(((_idx16+((( - x_max)-2)*y_max))-x_max)-2);
					u_0_1[_idx12]=((alpha*u_0_0[_idx12])+(beta*((u_0_0[_idx13]+(u_0_0[_idx14]+u_0_0[_idx15]))+(u_0_0[_idx16]+(u_0_0[_idx17]+u_0_0[_idx18])))));
				}
			}
		}
	}
#pragma omp barrier 
	( * u_0_1_out)=u_0_1;
}

void laplacian___unroll_p2_10101(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, float alpha, float beta, int x_max, int y_max, int z_max, int chunk)
{
	int _idx0;
	int _idx1;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx2;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int end0;
	int numthds0;
	int p2_embed_blkidx_x;
	int p2_embed_blkidx_x_idxouter;
	int p2_embed_idx_x;
	int p2_embed_idx_x_max;
	int p2_embed_idx_y;
	int p2_embed_idx_y_max;
	int p2_embed_idx_z;
	int p2_embed_idx_z_max;
	int p2_idx_x;
	int p2_idx_y;
	int p2_idx_z;
	int prologueend1;
	__m128 splat0 = _mm_load1_ps(( & alpha));
	__m128 splat1 = _mm_load1_ps(( & beta));
	int start0;
	int stepouter0;
	int tmp_stride_0z;
	int tmpidxc0;
	__m128 u_0_0_minus_1__m4_0_0__offs_0_0_0;
	__m128 u_0_0_plus_1__0_0_0__offs_0_0_0;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	start0=omp_get_thread_num();
	end0=(((((int)(((2*x_max)-1)/x_max))*((int)y_max))*((int)z_max))-1);
	numthds0=omp_get_num_threads();
	stepouter0=(chunk*numthds0);
	/*
	for p2_embed_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
	*/
	for (p2_embed_blkidx_x_idxouter=(start0*chunk); p2_embed_blkidx_x_idxouter<=end0; p2_embed_blkidx_x_idxouter+=stepouter0)
	{
		/*
		for p2_embed_blkidx_x = p2_embed_blkidx_x_idxouter..min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (p2_embed_blkidx_x=p2_embed_blkidx_x_idxouter; p2_embed_blkidx_x<=min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)); p2_embed_blkidx_x+=1)
		{
			tmp_stride_0z=(((int)(((2*x_max)-1)/x_max))*((int)(y_max/1)));
			p2_embed_idx_z=(p2_embed_blkidx_x/tmp_stride_0z);
			tmpidxc0=(p2_embed_blkidx_x-(p2_embed_idx_z*tmp_stride_0z));
			p2_embed_idx_y=(tmpidxc0/((int)(((2*x_max)-1)/x_max)));
			tmpidxc0-=(p2_embed_idx_y*((int)(((2*x_max)-1)/x_max)));
			p2_embed_idx_x=tmpidxc0;
			p2_embed_idx_x=((p2_embed_idx_x*x_max)+1);
			p2_embed_idx_x_max=min((p2_embed_idx_x+x_max), (x_max+1));
			p2_embed_idx_y=((p2_embed_idx_y*1)+1);
			p2_embed_idx_y_max=min((p2_embed_idx_y+1), (y_max+1));
			p2_embed_idx_z=((p2_embed_idx_z*1)+1);
			p2_embed_idx_z_max=min((p2_embed_idx_z+1), (z_max+1));
			/* Index bounds calculations for iterators in p2_embed[t=t][0] */
			/*
			for POINT p2[t=t][0] of size [1, 1, 1] in p2_embed[t=t][0] + [ min=[0, 0, 0], max=[0, 0, 0] ] parallel 1 <level 1> schedule default { ... }
			*/
			{
				/* Index bounds calculations for iterators in p2[t=t][0] */
				p2_idx_z=p2_embed_idx_z;
				p2_idx_y=p2_embed_idx_y;
				p2_idx_x=p2_embed_idx_x;
				/* _idx0 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
				_idx0=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
				prologueend1=min((p2_embed_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), p2_embed_idx_x_max);
				for (p2_idx_x=p2_embed_idx_x; p2_idx_x<prologueend1; p2_idx_x ++ )
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx12 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx12=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx13 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+1)) */
					_idx13=(_idx12+1);
					/* _idx14 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1)) */
					_idx14=(_idx12-1);
					/* _idx15 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx15=((_idx12+x_max)+2);
					/* _idx16 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx16=((_idx12-x_max)-2);
					/* _idx17 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx17=(((_idx16+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx18 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx18=(((_idx16+((( - x_max)-2)*y_max))-x_max)-2);
					u_0_1[_idx12]=((alpha*u_0_0[_idx12])+(beta*((u_0_0[_idx13]+(u_0_0[_idx14]+u_0_0[_idx15]))+(u_0_0[_idx16]+(u_0_0[_idx17]+u_0_0[_idx18])))));
				}
				for (; p2_idx_x<(p2_embed_idx_x_max-3); p2_idx_x+=4)
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx0 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx0=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx1 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+4)) */
					_idx1=(_idx0+4);
					u_0_0_plus_1__0_0_0__offs_0_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx1]))), 15), 137);
					/* _idx2 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-4)) */
					_idx2=(_idx1-8);
					u_0_0_minus_1__m4_0_0__offs_0_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
					/* _idx3 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx3=((_idx1+x_max)-2);
					/* _idx4 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx4=((_idx2-x_max)+2);
					/* _idx5 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx5=(((_idx4+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx6 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx6=(((_idx4+((( - x_max)-2)*y_max))-x_max)-2);
					( * ((__m128 * )( & u_0_1[_idx0])))=_mm_add_ps(_mm_mul_ps(splat0, ( * ((__m128 * )( & u_0_0[_idx0])))), _mm_mul_ps(splat1, _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0_0__offs_0_0_0, _mm_add_ps(u_0_0_minus_1__m4_0_0__offs_0_0_0, ( * ((__m128 * )( & u_0_0[_idx3]))))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx4]))), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx5]))), ( * ((__m128 * )( & u_0_0[_idx6]))))))));
				}
				for (; p2_idx_x<p2_embed_idx_x_max; p2_idx_x ++ )
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx12 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx12=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x);
					/* _idx13 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+1)) */
					_idx13=(_idx12+1);
					/* _idx14 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1)) */
					_idx14=(_idx12-1);
					/* _idx15 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx15=((_idx12+x_max)+2);
					/* _idx16 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx16=((_idx12-x_max)-2);
					/* _idx17 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx17=(((_idx16+((x_max+2)*y_max))+(3*x_max))+6);
					/* _idx18 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx18=(((_idx16+((( - x_max)-2)*y_max))-x_max)-2);
					u_0_1[_idx12]=((alpha*u_0_0[_idx12])+(beta*((u_0_0[_idx13]+(u_0_0[_idx14]+u_0_0[_idx15]))+(u_0_0[_idx16]+(u_0_0[_idx17]+u_0_0[_idx18])))));
				}
			}
		}
	}
#pragma omp barrier 
	( * u_0_1_out)=u_0_1;
}

static void (* g_rgCodeVariants0[])(float *  *  , float *  , float *  , float , float , int , int , int , int ) =  { laplacian___unroll_p2_20101, laplacian___unroll_p2_10101 } ;
/*
(u[0][0][0][1][0]=((alpha*u[0][0][0][0][0])+(beta*((u[1][0][0][0][0]+(u[-1][0][0][0][0]+u[0][1][0][0][0]))+(u[0][-1][0][0][0]+(u[0][0][1][0][0]+u[0][0][-1][0][0]))))))

*/
void laplacian(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, float alpha, float beta, int x_max, int y_max, int z_max, int chunk, int _unroll_p2)
{
	g_rgCodeVariants0[_unroll_p2](u_0_1_out, u_0_0, u_0_1, alpha, beta, x_max, y_max, z_max, chunk);
}

void initialize_laplacian(float *  u_0_0, float *  u_0_1, float alpha, float beta, int x_max, int y_max, int z_max, int chunk)
{
	int _idx0;
	int _idx1;
	int _idx2;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int end0;
	int numthds0;
	int p2_embed_blkidx_x;
	int p2_embed_blkidx_x_idxouter;
	int p2_embed_blkidx_y;
	int p2_embed_blkidx_z;
	int p2_embed_idx_x;
	int p2_embed_idx_x_max;
	int p2_embed_idx_y;
	int p2_embed_idx_y_max;
	int p2_embed_idx_z;
	int p2_embed_idx_z_max;
	int p2_idx_x;
	int p2_idx_y;
	int p2_idx_z;
	int start0;
	int stepouter0;
	int tmp_stride_0z;
	int tmp_stride_1z;
	int tmpidxc0;
	int tmpidxc1;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	start0=omp_get_thread_num();
	end0=(((((int)(((2*x_max)-1)/x_max))*((int)y_max))*((int)z_max))-1);
	numthds0=omp_get_num_threads();
	stepouter0=(chunk*numthds0);
	/*
	for p2_embed_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
	*/
	for (p2_embed_blkidx_x_idxouter=(start0*chunk); p2_embed_blkidx_x_idxouter<=end0; p2_embed_blkidx_x_idxouter+=stepouter0)
	{
		/*
		for p2_embed_blkidx_x = p2_embed_blkidx_x_idxouter..min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (p2_embed_blkidx_x=p2_embed_blkidx_x_idxouter; p2_embed_blkidx_x<=min(end0, ((p2_embed_blkidx_x_idxouter+chunk)-1)); p2_embed_blkidx_x+=1)
		{
			tmp_stride_1z=(((int)(((2*x_max)-1)/x_max))*((int)(y_max/1)));
			p2_embed_idx_z=(p2_embed_blkidx_x/tmp_stride_1z);
			tmpidxc1=(p2_embed_blkidx_x-(p2_embed_idx_z*tmp_stride_1z));
			p2_embed_idx_y=(tmpidxc1/((int)(((2*x_max)-1)/x_max)));
			tmpidxc1-=(p2_embed_idx_y*((int)(((2*x_max)-1)/x_max)));
			p2_embed_idx_x=tmpidxc1;
			p2_embed_idx_x=((p2_embed_idx_x*x_max)+1);
			p2_embed_idx_x_max=min((p2_embed_idx_x+x_max), (x_max+1));
			p2_embed_idx_y=((p2_embed_idx_y*1)+1);
			p2_embed_idx_y_max=min((p2_embed_idx_y+1), (y_max+1));
			p2_embed_idx_z=((p2_embed_idx_z*1)+1);
			p2_embed_idx_z_max=min((p2_embed_idx_z+1), (z_max+1));
			/* Index bounds calculations for iterators in p2_embed[t=t][0] */
			/*
			for POINT p2[t=t][0] of size [1, 1, 1] in p2_embed[t=t][0] + [ min=[0, 0, 0], max=[0, 0, 0] ] parallel 1 <level 1> schedule default { ... }
			*/
			{
				/* Index bounds calculations for iterators in p2[t=t][0] */
				p2_idx_z=p2_embed_idx_z;
				p2_idx_y=p2_embed_idx_y;
				for (p2_idx_x=p2_embed_idx_x; p2_idx_x<p2_embed_idx_x_max; p2_idx_x+=1)
				{
					/* Index bounds calculations for iterators in p2[t=t][0] */
					/*
					p2[t=(t+1)][0]=stencil(p2[t=t][0])
					*/
					/* _idx0 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1)) */
					_idx0=(((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x-1));
					u_0_0[_idx0]=(((1.0+((p2_idx_x+-1)*0.1))+(p2_idx_y*0.01))+(p2_idx_z*0.0010));
					/* _idx1 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y-1)))+p2_idx_x) */
					_idx1=((_idx0-x_max)-1);
					u_0_0[_idx1]=(((1.0+(p2_idx_x*0.1))+((p2_idx_y+-1)*0.01))+(p2_idx_z*0.0010));
					/* _idx2 = (((x_max+2)*(((y_max+2)*(p2_idx_z-1))+p2_idx_y))+p2_idx_x) */
					_idx2=(((_idx1+((( - x_max)-2)*y_max))-x_max)-2);
					u_0_0[_idx2]=(((1.0+(p2_idx_x*0.1))+(p2_idx_y*0.01))+((p2_idx_z+-1)*0.0010));
					/* _idx3 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+p2_idx_x) */
					_idx3=((_idx1+x_max)+2);
					u_0_0[_idx3]=(((1.0+(p2_idx_x*0.1))+(p2_idx_y*0.01))+(p2_idx_z*0.0010));
					/* _idx4 = (((x_max+2)*(((y_max+2)*(p2_idx_z+1))+p2_idx_y))+p2_idx_x) */
					_idx4=(((_idx1+((x_max+2)*y_max))+(3*x_max))+6);
					u_0_0[_idx4]=(((1.0+(p2_idx_x*0.1))+(p2_idx_y*0.01))+((p2_idx_z+1)*0.0010));
					/* _idx5 = (((x_max+2)*(((y_max+2)*p2_idx_z)+(p2_idx_y+1)))+p2_idx_x) */
					_idx5=((_idx3+x_max)+2);
					u_0_0[_idx5]=(((1.0+(p2_idx_x*0.1))+((p2_idx_y+1)*0.01))+(p2_idx_z*0.0010));
					/* _idx6 = (((x_max+2)*(((y_max+2)*p2_idx_z)+p2_idx_y))+(p2_idx_x+1)) */
					_idx6=((_idx1+x_max)+3);
					u_0_0[_idx6]=(((1.0+((p2_idx_x+1)*0.1))+(p2_idx_y*0.01))+(p2_idx_z*0.0010));
					u_0_1[_idx3]=(((11.0+(p2_idx_x*0.1))+(p2_idx_y*0.01))+(p2_idx_z*0.0010));
				}
			}
		}
	}
#pragma omp barrier 
}

