//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 05:45:06 PM CEST 
//


package ch.unibas.cs.hpwc.patus.arch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeRegisterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeRegisterType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="gpr"/>
 *     &lt;enumeration value="fpr"/>
 *     &lt;enumeration value="simd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeRegisterType {

    @XmlEnumValue("gpr")
    GPR("gpr"),
    @XmlEnumValue("fpr")
    FPR("fpr"),
    @XmlEnumValue("simd")
    SIMD("simd");
    private final String value;

    TypeRegisterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRegisterType fromValue(String v) {
        for (TypeRegisterType c: TypeRegisterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
