//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 05:45:06 PM CEST 
//


package ch.unibas.cs.hpwc.patus.arch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeArchitectureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeArchitectureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codegenerator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="src-suffix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="backend" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="innermost-loop-cg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="use-function-pointers" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="parallelism" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="level" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="barrier" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="type" use="required" type="{}typeCgType" />
 *                                     &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="has-explicit-local-datacopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="requires-synchronization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="async-IO" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datatypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="datatype" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="simd-vector-length" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                           &lt;attribute name="basetype" use="required" type="{}typeBaseDatatype" />
 *                           &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="alignment" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="declspecs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="declspec" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="type" use="required" type="{}typeDeclspec" />
 *                           &lt;attribute name="specifiers" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="intrinsics" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="intrinsic" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="base-name" use="required" type="{}typeBaseIntrinsicName" />
 *                           &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="arguments" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="latency" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *                           &lt;attribute name="exec-unit-type-ids" type="{}typeExecUnitTypeIDs" default="0" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="assembly" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="register-classes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="register-class" type="{}typeRegisterClass" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="registers" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="register" type="{}typeRegister" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="exec-unit-types" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="exec-unit-type" type="{}typeExecUnitType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="processor-issue-rate" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="includes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="include" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="build" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="compiler-command" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="harness-template-dir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inherits-from" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeArchitectureType", propOrder = {
    "codegenerator",
    "parallelism",
    "datatypes",
    "declspecs",
    "intrinsics",
    "assembly",
    "includes",
    "build"
})
public class TypeArchitectureType {

    protected TypeArchitectureType.Codegenerator codegenerator;
    protected TypeArchitectureType.Parallelism parallelism;
    protected TypeArchitectureType.Datatypes datatypes;
    protected TypeArchitectureType.Declspecs declspecs;
    protected TypeArchitectureType.Intrinsics intrinsics;
    protected TypeArchitectureType.Assembly assembly;
    protected TypeArchitectureType.Includes includes;
    protected TypeArchitectureType.Build build;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "inherits-from")
    protected String inheritsFrom;

    /**
     * Gets the value of the codegenerator property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Codegenerator }
     *     
     */
    public TypeArchitectureType.Codegenerator getCodegenerator() {
        return codegenerator;
    }

    /**
     * Sets the value of the codegenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Codegenerator }
     *     
     */
    public void setCodegenerator(TypeArchitectureType.Codegenerator value) {
        this.codegenerator = value;
    }

    /**
     * Gets the value of the parallelism property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Parallelism }
     *     
     */
    public TypeArchitectureType.Parallelism getParallelism() {
        return parallelism;
    }

    /**
     * Sets the value of the parallelism property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Parallelism }
     *     
     */
    public void setParallelism(TypeArchitectureType.Parallelism value) {
        this.parallelism = value;
    }

    /**
     * Gets the value of the datatypes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Datatypes }
     *     
     */
    public TypeArchitectureType.Datatypes getDatatypes() {
        return datatypes;
    }

    /**
     * Sets the value of the datatypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Datatypes }
     *     
     */
    public void setDatatypes(TypeArchitectureType.Datatypes value) {
        this.datatypes = value;
    }

    /**
     * Gets the value of the declspecs property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Declspecs }
     *     
     */
    public TypeArchitectureType.Declspecs getDeclspecs() {
        return declspecs;
    }

    /**
     * Sets the value of the declspecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Declspecs }
     *     
     */
    public void setDeclspecs(TypeArchitectureType.Declspecs value) {
        this.declspecs = value;
    }

    /**
     * Gets the value of the intrinsics property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Intrinsics }
     *     
     */
    public TypeArchitectureType.Intrinsics getIntrinsics() {
        return intrinsics;
    }

    /**
     * Sets the value of the intrinsics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Intrinsics }
     *     
     */
    public void setIntrinsics(TypeArchitectureType.Intrinsics value) {
        this.intrinsics = value;
    }

    /**
     * Gets the value of the assembly property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Assembly }
     *     
     */
    public TypeArchitectureType.Assembly getAssembly() {
        return assembly;
    }

    /**
     * Sets the value of the assembly property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Assembly }
     *     
     */
    public void setAssembly(TypeArchitectureType.Assembly value) {
        this.assembly = value;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Includes }
     *     
     */
    public TypeArchitectureType.Includes getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Includes }
     *     
     */
    public void setIncludes(TypeArchitectureType.Includes value) {
        this.includes = value;
    }

    /**
     * Gets the value of the build property.
     * 
     * @return
     *     possible object is
     *     {@link TypeArchitectureType.Build }
     *     
     */
    public TypeArchitectureType.Build getBuild() {
        return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeArchitectureType.Build }
     *     
     */
    public void setBuild(TypeArchitectureType.Build value) {
        this.build = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inheritsFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritsFrom() {
        return inheritsFrom;
    }

    /**
     * Sets the value of the inheritsFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritsFrom(String value) {
        this.inheritsFrom = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="register-classes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="register-class" type="{}typeRegisterClass" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="registers" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="register" type="{}typeRegister" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="exec-unit-types" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="exec-unit-type" type="{}typeExecUnitType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="processor-issue-rate" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registerClasses",
        "registers",
        "execUnitTypes"
    })
    public static class Assembly {

        @XmlElement(name = "register-classes")
        protected TypeArchitectureType.Assembly.RegisterClasses registerClasses;
        protected TypeArchitectureType.Assembly.Registers registers;
        @XmlElement(name = "exec-unit-types")
        protected TypeArchitectureType.Assembly.ExecUnitTypes execUnitTypes;
        @XmlAttribute(name = "processor-issue-rate")
        protected Integer processorIssueRate;

        /**
         * Gets the value of the registerClasses property.
         * 
         * @return
         *     possible object is
         *     {@link TypeArchitectureType.Assembly.RegisterClasses }
         *     
         */
        public TypeArchitectureType.Assembly.RegisterClasses getRegisterClasses() {
            return registerClasses;
        }

        /**
         * Sets the value of the registerClasses property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeArchitectureType.Assembly.RegisterClasses }
         *     
         */
        public void setRegisterClasses(TypeArchitectureType.Assembly.RegisterClasses value) {
            this.registerClasses = value;
        }

        /**
         * Gets the value of the registers property.
         * 
         * @return
         *     possible object is
         *     {@link TypeArchitectureType.Assembly.Registers }
         *     
         */
        public TypeArchitectureType.Assembly.Registers getRegisters() {
            return registers;
        }

        /**
         * Sets the value of the registers property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeArchitectureType.Assembly.Registers }
         *     
         */
        public void setRegisters(TypeArchitectureType.Assembly.Registers value) {
            this.registers = value;
        }

        /**
         * Gets the value of the execUnitTypes property.
         * 
         * @return
         *     possible object is
         *     {@link TypeArchitectureType.Assembly.ExecUnitTypes }
         *     
         */
        public TypeArchitectureType.Assembly.ExecUnitTypes getExecUnitTypes() {
            return execUnitTypes;
        }

        /**
         * Sets the value of the execUnitTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeArchitectureType.Assembly.ExecUnitTypes }
         *     
         */
        public void setExecUnitTypes(TypeArchitectureType.Assembly.ExecUnitTypes value) {
            this.execUnitTypes = value;
        }

        /**
         * Gets the value of the processorIssueRate property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getProcessorIssueRate() {
            if (processorIssueRate == null) {
                return  1;
            } else {
                return processorIssueRate;
            }
        }

        /**
         * Sets the value of the processorIssueRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setProcessorIssueRate(Integer value) {
            this.processorIssueRate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="exec-unit-type" type="{}typeExecUnitType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "execUnitType"
        })
        public static class ExecUnitTypes {

            @XmlElement(name = "exec-unit-type")
            protected List<TypeExecUnitType> execUnitType;

            /**
             * Gets the value of the execUnitType property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the execUnitType property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExecUnitType().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TypeExecUnitType }
             * 
             * 
             */
            public List<TypeExecUnitType> getExecUnitType() {
                if (execUnitType == null) {
                    execUnitType = new ArrayList<TypeExecUnitType>();
                }
                return this.execUnitType;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="register-class" type="{}typeRegisterClass" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "registerClass"
        })
        public static class RegisterClasses {

            @XmlElement(name = "register-class")
            protected List<TypeRegisterClass> registerClass;

            /**
             * Gets the value of the registerClass property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the registerClass property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRegisterClass().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TypeRegisterClass }
             * 
             * 
             */
            public List<TypeRegisterClass> getRegisterClass() {
                if (registerClass == null) {
                    registerClass = new ArrayList<TypeRegisterClass>();
                }
                return this.registerClass;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="register" type="{}typeRegister" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "register"
        })
        public static class Registers {

            protected List<TypeRegister> register;

            /**
             * Gets the value of the register property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the register property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRegister().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TypeRegister }
             * 
             * 
             */
            public List<TypeRegister> getRegister() {
                if (register == null) {
                    register = new ArrayList<TypeRegister>();
                }
                return this.register;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="compiler-command" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="harness-template-dir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Build {

        @XmlAttribute(name = "compiler-command", required = true)
        protected String compilerCommand;
        @XmlAttribute(name = "harness-template-dir", required = true)
        protected String harnessTemplateDir;

        /**
         * Gets the value of the compilerCommand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompilerCommand() {
            return compilerCommand;
        }

        /**
         * Sets the value of the compilerCommand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompilerCommand(String value) {
            this.compilerCommand = value;
        }

        /**
         * Gets the value of the harnessTemplateDir property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHarnessTemplateDir() {
            return harnessTemplateDir;
        }

        /**
         * Sets the value of the harnessTemplateDir property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHarnessTemplateDir(String value) {
            this.harnessTemplateDir = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="src-suffix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="backend" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="innermost-loop-cg" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="use-function-pointers" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Codegenerator {

        @XmlAttribute(name = "src-suffix", required = true)
        protected String srcSuffix;
        @XmlAttribute(required = true)
        protected String backend;
        @XmlAttribute(name = "innermost-loop-cg")
        protected String innermostLoopCg;
        @XmlAttribute(name = "use-function-pointers", required = true)
        protected boolean useFunctionPointers;

        /**
         * Gets the value of the srcSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcSuffix() {
            return srcSuffix;
        }

        /**
         * Sets the value of the srcSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcSuffix(String value) {
            this.srcSuffix = value;
        }

        /**
         * Gets the value of the backend property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackend() {
            return backend;
        }

        /**
         * Sets the value of the backend property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackend(String value) {
            this.backend = value;
        }

        /**
         * Gets the value of the innermostLoopCg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInnermostLoopCg() {
            return innermostLoopCg;
        }

        /**
         * Sets the value of the innermostLoopCg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInnermostLoopCg(String value) {
            this.innermostLoopCg = value;
        }

        /**
         * Gets the value of the useFunctionPointers property.
         * 
         */
        public boolean isUseFunctionPointers() {
            return useFunctionPointers;
        }

        /**
         * Sets the value of the useFunctionPointers property.
         * 
         */
        public void setUseFunctionPointers(boolean value) {
            this.useFunctionPointers = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="datatype" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="simd-vector-length" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                 &lt;attribute name="basetype" use="required" type="{}typeBaseDatatype" />
     *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="alignment" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datatype"
    })
    public static class Datatypes {

        protected List<TypeArchitectureType.Datatypes.Datatype> datatype;

        /**
         * Gets the value of the datatype property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datatype property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatatype().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeArchitectureType.Datatypes.Datatype }
         * 
         * 
         */
        public List<TypeArchitectureType.Datatypes.Datatype> getDatatype() {
            if (datatype == null) {
                datatype = new ArrayList<TypeArchitectureType.Datatypes.Datatype>();
            }
            return this.datatype;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="simd-vector-length" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *       &lt;attribute name="basetype" use="required" type="{}typeBaseDatatype" />
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="alignment" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Datatype {

            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(name = "simd-vector-length")
            protected Integer simdVectorLength;
            @XmlAttribute(required = true)
            protected TypeBaseDatatype basetype;
            @XmlAttribute(required = true)
            protected int width;
            @XmlAttribute
            protected Integer alignment;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the simdVectorLength property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getSimdVectorLength() {
                if (simdVectorLength == null) {
                    return  1;
                } else {
                    return simdVectorLength;
                }
            }

            /**
             * Sets the value of the simdVectorLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSimdVectorLength(Integer value) {
                this.simdVectorLength = value;
            }

            /**
             * Gets the value of the basetype property.
             * 
             * @return
             *     possible object is
             *     {@link TypeBaseDatatype }
             *     
             */
            public TypeBaseDatatype getBasetype() {
                return basetype;
            }

            /**
             * Sets the value of the basetype property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeBaseDatatype }
             *     
             */
            public void setBasetype(TypeBaseDatatype value) {
                this.basetype = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public int getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(int value) {
                this.width = value;
            }

            /**
             * Gets the value of the alignment property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getAlignment() {
                return alignment;
            }

            /**
             * Sets the value of the alignment property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setAlignment(Integer value) {
                this.alignment = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="declspec" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="type" use="required" type="{}typeDeclspec" />
     *                 &lt;attribute name="specifiers" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "declspec"
    })
    public static class Declspecs {

        protected List<TypeArchitectureType.Declspecs.Declspec> declspec;

        /**
         * Gets the value of the declspec property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the declspec property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeclspec().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeArchitectureType.Declspecs.Declspec }
         * 
         * 
         */
        public List<TypeArchitectureType.Declspecs.Declspec> getDeclspec() {
            if (declspec == null) {
                declspec = new ArrayList<TypeArchitectureType.Declspecs.Declspec>();
            }
            return this.declspec;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="type" use="required" type="{}typeDeclspec" />
         *       &lt;attribute name="specifiers" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Declspec {

            @XmlAttribute(required = true)
            protected TypeDeclspec type;
            @XmlAttribute(required = true)
            protected String specifiers;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link TypeDeclspec }
             *     
             */
            public TypeDeclspec getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeDeclspec }
             *     
             */
            public void setType(TypeDeclspec value) {
                this.type = value;
            }

            /**
             * Gets the value of the specifiers property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecifiers() {
                return specifiers;
            }

            /**
             * Sets the value of the specifiers property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecifiers(String value) {
                this.specifiers = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="include" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "include"
    })
    public static class Includes {

        protected List<TypeArchitectureType.Includes.Include> include;

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeArchitectureType.Includes.Include }
         * 
         * 
         */
        public List<TypeArchitectureType.Includes.Include> getInclude() {
            if (include == null) {
                include = new ArrayList<TypeArchitectureType.Includes.Include>();
            }
            return this.include;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Include {

            @XmlAttribute(required = true)
            protected String file;

            /**
             * Gets the value of the file property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFile() {
                return file;
            }

            /**
             * Sets the value of the file property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFile(String value) {
                this.file = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="intrinsic" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="base-name" use="required" type="{}typeBaseIntrinsicName" />
     *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="arguments" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="latency" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
     *                 &lt;attribute name="exec-unit-type-ids" type="{}typeExecUnitTypeIDs" default="0" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "intrinsic"
    })
    public static class Intrinsics {

        protected List<TypeArchitectureType.Intrinsics.Intrinsic> intrinsic;

        /**
         * Gets the value of the intrinsic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the intrinsic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIntrinsic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeArchitectureType.Intrinsics.Intrinsic }
         * 
         * 
         */
        public List<TypeArchitectureType.Intrinsics.Intrinsic> getIntrinsic() {
            if (intrinsic == null) {
                intrinsic = new ArrayList<TypeArchitectureType.Intrinsics.Intrinsic>();
            }
            return this.intrinsic;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="base-name" use="required" type="{}typeBaseIntrinsicName" />
         *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="arguments" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="latency" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
         *       &lt;attribute name="exec-unit-type-ids" type="{}typeExecUnitTypeIDs" default="0" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Intrinsic {

            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(name = "base-name", required = true)
            protected String baseName;
            @XmlAttribute(required = true)
            protected String datatype;
            @XmlAttribute
            protected String arguments;
            @XmlAttribute
            protected Integer latency;
            @XmlAttribute(name = "exec-unit-type-ids")
            protected List<Integer> execUnitTypeIds;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the baseName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBaseName() {
                return baseName;
            }

            /**
             * Sets the value of the baseName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBaseName(String value) {
                this.baseName = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

            /**
             * Gets the value of the arguments property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArguments() {
                return arguments;
            }

            /**
             * Sets the value of the arguments property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArguments(String value) {
                this.arguments = value;
            }

            /**
             * Gets the value of the latency property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getLatency() {
                if (latency == null) {
                    return  1;
                } else {
                    return latency;
                }
            }

            /**
             * Sets the value of the latency property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLatency(Integer value) {
                this.latency = value;
            }

            /**
             * Gets the value of the execUnitTypeIds property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the execUnitTypeIds property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExecUnitTypeIds().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getExecUnitTypeIds() {
                if (execUnitTypeIds == null) {
                    execUnitTypeIds = new ArrayList<Integer>();
                }
                return this.execUnitTypeIds;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="level" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="barrier" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="type" use="required" type="{}typeCgType" />
     *                           &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="has-explicit-local-datacopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="requires-synchronization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="async-IO" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "level"
    })
    public static class Parallelism {

        @XmlElement(required = true)
        protected List<TypeArchitectureType.Parallelism.Level> level;

        /**
         * Gets the value of the level property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the level property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeArchitectureType.Parallelism.Level }
         * 
         * 
         */
        public List<TypeArchitectureType.Parallelism.Level> getLevel() {
            if (level == null) {
                level = new ArrayList<TypeArchitectureType.Parallelism.Level>();
            }
            return this.level;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="barrier" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="type" use="required" type="{}typeCgType" />
         *                 &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="has-explicit-local-datacopy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="requires-synchronization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="async-IO" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "barrier"
        })
        public static class Level {

            protected TypeArchitectureType.Parallelism.Level.Barrier barrier;
            @XmlAttribute(required = true)
            protected int number;
            @XmlAttribute
            protected String name;
            @XmlAttribute(name = "has-explicit-local-datacopy")
            protected Boolean hasExplicitLocalDatacopy;
            @XmlAttribute(name = "requires-synchronization")
            protected Boolean requiresSynchronization;
            @XmlAttribute(name = "async-IO")
            protected Boolean asyncIO;

            /**
             * Gets the value of the barrier property.
             * 
             * @return
             *     possible object is
             *     {@link TypeArchitectureType.Parallelism.Level.Barrier }
             *     
             */
            public TypeArchitectureType.Parallelism.Level.Barrier getBarrier() {
                return barrier;
            }

            /**
             * Sets the value of the barrier property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeArchitectureType.Parallelism.Level.Barrier }
             *     
             */
            public void setBarrier(TypeArchitectureType.Parallelism.Level.Barrier value) {
                this.barrier = value;
            }

            /**
             * Gets the value of the number property.
             * 
             */
            public int getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             */
            public void setNumber(int value) {
                this.number = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the hasExplicitLocalDatacopy property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isHasExplicitLocalDatacopy() {
                if (hasExplicitLocalDatacopy == null) {
                    return false;
                } else {
                    return hasExplicitLocalDatacopy;
                }
            }

            /**
             * Sets the value of the hasExplicitLocalDatacopy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setHasExplicitLocalDatacopy(Boolean value) {
                this.hasExplicitLocalDatacopy = value;
            }

            /**
             * Gets the value of the requiresSynchronization property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isRequiresSynchronization() {
                if (requiresSynchronization == null) {
                    return false;
                } else {
                    return requiresSynchronization;
                }
            }

            /**
             * Sets the value of the requiresSynchronization property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setRequiresSynchronization(Boolean value) {
                this.requiresSynchronization = value;
            }

            /**
             * Gets the value of the asyncIO property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isAsyncIO() {
                if (asyncIO == null) {
                    return false;
                } else {
                    return asyncIO;
                }
            }

            /**
             * Sets the value of the asyncIO property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAsyncIO(Boolean value) {
                this.asyncIO = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="type" use="required" type="{}typeCgType" />
             *       &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Barrier {

                @XmlAttribute(required = true)
                protected TypeCgType type;
                @XmlAttribute(required = true)
                protected String implementation;

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeCgType }
                 *     
                 */
                public TypeCgType getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeCgType }
                 *     
                 */
                public void setType(TypeCgType value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the implementation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getImplementation() {
                    return implementation;
                }

                /**
                 * Sets the value of the implementation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setImplementation(String value) {
                    this.implementation = value;
                }

            }

        }

    }

}
