//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 05:45:06 PM CEST 
//


package ch.unibas.cs.hpwc.patus.arch;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for typeCgType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCgType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pragma"/>
 *     &lt;enumeration value="functioncall"/>
 *     &lt;enumeration value="statement"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TypeCgType {

    @XmlEnumValue("pragma")
    PRAGMA("pragma"),
    @XmlEnumValue("functioncall")
    FUNCTIONCALL("functioncall"),
    @XmlEnumValue("statement")
    STATEMENT("statement");
    private final String value;

    TypeCgType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCgType fromValue(String v) {
        for (TypeCgType c: TypeCgType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
