/**
 * Kernel and initialization code for the stencil
 *
 * (L[0][0]=(((u[-1][-1][0][0]+u[0][-1][0][0])+(u[1][-1][0][0]+u[-1][0][0][0]))+((u[1][0][0][0]+u[-1][1][0][0])+(u[0][1][0][0]+u[1][1][0][0]))))
 * (u[0][0][1][0]=(1.0/((((u[0][0][0][0]+L)-3.0)*((L-3.0)*1.0E20))+1.0)))
 * 
 * Strategy: C:\Users\Matthias\Projects\Java\Patus-GoogleCode\strategy\cacheblocked.stg
 * 
 * This code was generated by Patus on 2011/09/01 10:01:05
 */

#include "omp.h"
#include "xmmintrin.h"
#include "emmintrin.h"
#include <stdint.h>

void game_of_life___unroll_p3_102(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk)
{
	float L;
	float L_unroll_1;
	__m128 L_vec_0;
	__m128 L_vec_1;
	int _idx0;
	int _idx1;
	int _idx10;
	int _idx11;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx19;
	int _idx2;
	int _idx20;
	int _idx21;
	int _idx22;
	int _idx23;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int _idx9;
	int end0;
	int numthds0;
	int p3_idx_x;
	int p3_idx_y;
	int prologueend0;
	int prologueend1;
	__m128 splat0 =  { 1.0f, 1.0f, 1.0f, 1.0f } ;
	__m128 splat1 =  { 3.0f, 3.0f, 3.0f, 3.0f } ;
	__m128 splat2 =  { 1.0E20f, 1.0E20f, 1.0E20f, 1.0E20f } ;
	int start0;
	int stepouter0;
	int t;
	float *  tmp_swap_1;
	int tmpidxc0;
	__m128 u_0_0_minus_1__m4_0__offs_0_0;
	__m128 u_0_0_minus_1__m4_1__offs_0_0;
	__m128 u_0_0_minus_1__m4_2__offs_0_1;
	__m128 u_0_0_minus_1__m4_m1__offs_0_0;
	__m128 u_0_0_plus_1__0_0__offs_0_0;
	__m128 u_0_0_plus_1__0_1__offs_0_0;
	__m128 u_0_0_plus_1__0_2__offs_0_1;
	__m128 u_0_0_plus_1__0_m1__offs_0_0;
	int v2_blkidx_x;
	int v2_blkidx_x_idxouter;
	int v2_idx_x;
	int v2_idx_x_max;
	int v2_idx_y;
	int v2_idx_y_max;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	/*
	for t = 1..100 by 1 parallel 1 <level 0> schedule 1 { ... }
	*/
	for (t=1; t<=100; t+=1)
	{
		start0=omp_get_thread_num();
		end0=((((int)(((width+cb_x)-1)/cb_x))*((int)(((height+cb_y)-1)/cb_y)))-1);
		numthds0=omp_get_num_threads();
		stepouter0=(chunk*numthds0);
		/*
		for v2_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (v2_blkidx_x_idxouter=(start0*chunk); v2_blkidx_x_idxouter<=end0; v2_blkidx_x_idxouter+=stepouter0)
		{
			/*
			for v2_blkidx_x = v2_blkidx_x_idxouter..min(end0, ((v2_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
			*/
			for (v2_blkidx_x=v2_blkidx_x_idxouter; v2_blkidx_x<=min(end0, ((v2_blkidx_x_idxouter+chunk)-1)); v2_blkidx_x+=1)
			{
				v2_idx_y=(v2_blkidx_x/((int)(((width+cb_x)-1)/cb_x)));
				tmpidxc0=(v2_blkidx_x-(v2_idx_y*((int)(((width+cb_x)-1)/cb_x))));
				v2_idx_x=tmpidxc0;
				v2_idx_x=((v2_idx_x*cb_x)+1);
				v2_idx_x_max=min((v2_idx_x+cb_x), (width+1));
				v2_idx_y=((v2_idx_y*cb_y)+1);
				v2_idx_y_max=min((v2_idx_y+cb_y), (height+1));
				/* Index bounds calculations for iterators in v2[t=t][0] */
				/*
				for POINT p3[t=t][0] of size [1, 1] in v2[t=t][0] + [ min=[0, 0], max=[0, 0] ] parallel 1 <level 1> schedule default { ... }
				*/
				{
					/* Index bounds calculations for iterators in p3[t=t][0] */
					for (p3_idx_y=v2_idx_y; p3_idx_y<(v2_idx_y_max-1); p3_idx_y+=2)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend0=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend0; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							/* _idx21 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-1)) */
							_idx21=(_idx19+width);
							/* _idx22 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx22=((_idx19+width)+1);
							/* _idx23 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+1)) */
							_idx23=((_idx19+width)+2);
							L_unroll_1=(((u_0_0[_idx15]+u_0_0[_idx20])+(u_0_0[_idx16]+u_0_0[_idx17]))+((u_0_0[_idx19]+u_0_0[_idx21])+(u_0_0[_idx22]+u_0_0[_idx23])));
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
							u_0_1[_idx18]=(1.0f/((((u_0_0[_idx18]+L_unroll_1)-3.0f)*((L_unroll_1-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-3); p3_idx_x+=4)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							/* _idx9 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-4)) */
							_idx9=((_idx8+width)-6);
							/* _idx10 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx10=(_idx9+4);
							u_0_0_minus_1__m4_2__offs_0_1=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx9]))), ( * ((__m128 * )( & u_0_0[_idx10]))), 15), ( * ((__m128 * )( & u_0_0[_idx10]))), 152);
							/* _idx11 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+4)) */
							_idx11=(_idx9+8);
							u_0_0_plus_1__0_2__offs_0_1=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx10]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx10]))), ( * ((__m128 * )( & u_0_0[_idx11]))), 15), 137);
							L_vec_1=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_0__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx0])))), _mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_1__offs_0_0, u_0_0_minus_1__m4_2__offs_0_1), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx10]))), u_0_0_plus_1__0_2__offs_0_1)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx7])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), L_vec_1), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_1, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							/* _idx21 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-1)) */
							_idx21=(_idx19+width);
							/* _idx22 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx22=((_idx19+width)+1);
							/* _idx23 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+1)) */
							_idx23=((_idx19+width)+2);
							L_unroll_1=(((u_0_0[_idx15]+u_0_0[_idx20])+(u_0_0[_idx16]+u_0_0[_idx17]))+((u_0_0[_idx19]+u_0_0[_idx21])+(u_0_0[_idx22]+u_0_0[_idx23])));
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
							u_0_1[_idx18]=(1.0f/((((u_0_0[_idx18]+L_unroll_1)-3.0f)*((L_unroll_1-3.0f)*1.0E20f))+1.0f));
						}
					}
					for (; p3_idx_y<v2_idx_y_max; p3_idx_y+=1)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend1=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend1; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-3); p3_idx_x+=4)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
					}
				}
			}
		}
#pragma omp barrier 
		( * u_0_1_out)=u_0_1;
		tmp_swap_1=u_0_0;
		u_0_0=u_0_1;
		u_0_1=tmp_swap_1;
	}
}

void game_of_life___unroll_p3_201(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk)
{
	float L;
	__m128 L_vec_0;
	__m128 L_vec_1;
	int _idx0;
	int _idx1;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx19;
	int _idx2;
	int _idx20;
	int _idx24;
	int _idx25;
	int _idx26;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int _idx9;
	int end0;
	int numthds0;
	int p3_idx_x;
	int p3_idx_y;
	int prologueend5;
	__m128 splat0 =  { 1.0f, 1.0f, 1.0f, 1.0f } ;
	__m128 splat1 =  { 3.0f, 3.0f, 3.0f, 3.0f } ;
	__m128 splat2 =  { 1.0E20f, 1.0E20f, 1.0E20f, 1.0E20f } ;
	int start0;
	int stepouter0;
	int t;
	float *  tmp_swap_1;
	int tmpidxc0;
	__m128 u_0_0_minus_1__0_0__offs_4_0;
	__m128 u_0_0_minus_1__0_1__offs_4_0;
	__m128 u_0_0_minus_1__0_m1__offs_4_0;
	__m128 u_0_0_minus_1__m4_0__offs_0_0;
	__m128 u_0_0_minus_1__m4_1__offs_0_0;
	__m128 u_0_0_minus_1__m4_m1__offs_0_0;
	__m128 u_0_0_plus_1__0_0__offs_0_0;
	__m128 u_0_0_plus_1__0_1__offs_0_0;
	__m128 u_0_0_plus_1__0_m1__offs_0_0;
	__m128 u_0_0_plus_1__4_0__offs_4_0;
	__m128 u_0_0_plus_1__4_1__offs_4_0;
	__m128 u_0_0_plus_1__4_m1__offs_4_0;
	int v2_blkidx_x;
	int v2_blkidx_x_idxouter;
	int v2_idx_x;
	int v2_idx_x_max;
	int v2_idx_y;
	int v2_idx_y_max;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	/*
	for t = 1..100 by 1 parallel 1 <level 0> schedule 1 { ... }
	*/
	for (t=1; t<=100; t+=1)
	{
		start0=omp_get_thread_num();
		end0=((((int)(((width+cb_x)-1)/cb_x))*((int)(((height+cb_y)-1)/cb_y)))-1);
		numthds0=omp_get_num_threads();
		stepouter0=(chunk*numthds0);
		/*
		for v2_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (v2_blkidx_x_idxouter=(start0*chunk); v2_blkidx_x_idxouter<=end0; v2_blkidx_x_idxouter+=stepouter0)
		{
			/*
			for v2_blkidx_x = v2_blkidx_x_idxouter..min(end0, ((v2_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
			*/
			for (v2_blkidx_x=v2_blkidx_x_idxouter; v2_blkidx_x<=min(end0, ((v2_blkidx_x_idxouter+chunk)-1)); v2_blkidx_x+=1)
			{
				v2_idx_y=(v2_blkidx_x/((int)(((width+cb_x)-1)/cb_x)));
				tmpidxc0=(v2_blkidx_x-(v2_idx_y*((int)(((width+cb_x)-1)/cb_x))));
				v2_idx_x=tmpidxc0;
				v2_idx_x=((v2_idx_x*cb_x)+1);
				v2_idx_x_max=min((v2_idx_x+cb_x), (width+1));
				v2_idx_y=((v2_idx_y*cb_y)+1);
				v2_idx_y_max=min((v2_idx_y+cb_y), (height+1));
				/* Index bounds calculations for iterators in v2[t=t][0] */
				/*
				for POINT p3[t=t][0] of size [1, 1] in v2[t=t][0] + [ min=[0, 0], max=[0, 0] ] parallel 1 <level 1> schedule default { ... }
				*/
				{
					/* Index bounds calculations for iterators in p3[t=t][0] */
					for (p3_idx_y=v2_idx_y; p3_idx_y<v2_idx_y_max; p3_idx_y+=1)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend5=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend5; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-7); p3_idx_x+=8)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							u_0_0_minus_1__0_m1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), ( * ((__m128 * )( & u_0_0[_idx3]))), 152);
							/* _idx24 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+8)) */
							_idx24=((_idx4-width)+10);
							u_0_0_plus_1__4_m1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), ( * ((__m128 * )( & u_0_0[_idx24]))), 15), 137);
							u_0_0_minus_1__0_0__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), ( * ((__m128 * )( & u_0_0[_idx5]))), 152);
							/* _idx25 = (((width+2)*p3_idx_y)+(p3_idx_x+8)) */
							_idx25=(_idx4+12);
							u_0_0_plus_1__4_0__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), ( * ((__m128 * )( & u_0_0[_idx25]))), 15), 137);
							u_0_0_minus_1__0_1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), ( * ((__m128 * )( & u_0_0[_idx8]))), 152);
							/* _idx9 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-4)) */
							_idx9=((_idx8+width)-6);
							/* _idx26 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+8)) */
							_idx26=((_idx9-width)+10);
							u_0_0_plus_1__4_1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), ( * ((__m128 * )( & u_0_0[_idx26]))), 15), 137);
							L_vec_1=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__0_m1__offs_4_0, ( * ((__m128 * )( & u_0_0[_idx3])))), _mm_add_ps(u_0_0_plus_1__4_m1__offs_4_0, u_0_0_minus_1__0_0__offs_4_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__4_0__offs_4_0, u_0_0_minus_1__0_1__offs_4_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx8]))), u_0_0_plus_1__4_1__offs_4_0)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx5])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx5]))), L_vec_1), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_1, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
					}
				}
			}
		}
#pragma omp barrier 
		( * u_0_1_out)=u_0_1;
		tmp_swap_1=u_0_0;
		u_0_0=u_0_1;
		u_0_1=tmp_swap_1;
	}
}

void game_of_life___unroll_p3_101(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk)
{
	float L;
	__m128 L_vec_0;
	int _idx0;
	int _idx1;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx19;
	int _idx2;
	int _idx20;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int end0;
	int numthds0;
	int p3_idx_x;
	int p3_idx_y;
	int prologueend2;
	__m128 splat0 =  { 1.0f, 1.0f, 1.0f, 1.0f } ;
	__m128 splat1 =  { 3.0f, 3.0f, 3.0f, 3.0f } ;
	__m128 splat2 =  { 1.0E20f, 1.0E20f, 1.0E20f, 1.0E20f } ;
	int start0;
	int stepouter0;
	int t;
	float *  tmp_swap_1;
	int tmpidxc0;
	__m128 u_0_0_minus_1__m4_0__offs_0_0;
	__m128 u_0_0_minus_1__m4_1__offs_0_0;
	__m128 u_0_0_minus_1__m4_m1__offs_0_0;
	__m128 u_0_0_plus_1__0_0__offs_0_0;
	__m128 u_0_0_plus_1__0_1__offs_0_0;
	__m128 u_0_0_plus_1__0_m1__offs_0_0;
	int v2_blkidx_x;
	int v2_blkidx_x_idxouter;
	int v2_idx_x;
	int v2_idx_x_max;
	int v2_idx_y;
	int v2_idx_y_max;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	/*
	for t = 1..100 by 1 parallel 1 <level 0> schedule 1 { ... }
	*/
	for (t=1; t<=100; t+=1)
	{
		start0=omp_get_thread_num();
		end0=((((int)(((width+cb_x)-1)/cb_x))*((int)(((height+cb_y)-1)/cb_y)))-1);
		numthds0=omp_get_num_threads();
		stepouter0=(chunk*numthds0);
		/*
		for v2_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (v2_blkidx_x_idxouter=(start0*chunk); v2_blkidx_x_idxouter<=end0; v2_blkidx_x_idxouter+=stepouter0)
		{
			/*
			for v2_blkidx_x = v2_blkidx_x_idxouter..min(end0, ((v2_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
			*/
			for (v2_blkidx_x=v2_blkidx_x_idxouter; v2_blkidx_x<=min(end0, ((v2_blkidx_x_idxouter+chunk)-1)); v2_blkidx_x+=1)
			{
				v2_idx_y=(v2_blkidx_x/((int)(((width+cb_x)-1)/cb_x)));
				tmpidxc0=(v2_blkidx_x-(v2_idx_y*((int)(((width+cb_x)-1)/cb_x))));
				v2_idx_x=tmpidxc0;
				v2_idx_x=((v2_idx_x*cb_x)+1);
				v2_idx_x_max=min((v2_idx_x+cb_x), (width+1));
				v2_idx_y=((v2_idx_y*cb_y)+1);
				v2_idx_y_max=min((v2_idx_y+cb_y), (height+1));
				/* Index bounds calculations for iterators in v2[t=t][0] */
				/*
				for POINT p3[t=t][0] of size [1, 1] in v2[t=t][0] + [ min=[0, 0], max=[0, 0] ] parallel 1 <level 1> schedule default { ... }
				*/
				{
					/* Index bounds calculations for iterators in p3[t=t][0] */
					for (p3_idx_y=v2_idx_y; p3_idx_y<v2_idx_y_max; p3_idx_y+=1)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend2=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend2; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-3); p3_idx_x+=4)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
					}
				}
			}
		}
#pragma omp barrier 
		( * u_0_1_out)=u_0_1;
		tmp_swap_1=u_0_0;
		u_0_0=u_0_1;
		u_0_1=tmp_swap_1;
	}
}

void game_of_life___unroll_p3_202(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk)
{
	float L;
	float L_unroll_1;
	__m128 L_vec_0;
	__m128 L_vec_1;
	__m128 L_vec_2;
	__m128 L_vec_3;
	int _idx0;
	int _idx1;
	int _idx10;
	int _idx11;
	int _idx12;
	int _idx13;
	int _idx14;
	int _idx15;
	int _idx16;
	int _idx17;
	int _idx18;
	int _idx19;
	int _idx2;
	int _idx20;
	int _idx21;
	int _idx22;
	int _idx23;
	int _idx24;
	int _idx25;
	int _idx26;
	int _idx27;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int _idx9;
	int end0;
	int numthds0;
	int p3_idx_x;
	int p3_idx_y;
	int prologueend3;
	int prologueend4;
	__m128 splat0 =  { 1.0f, 1.0f, 1.0f, 1.0f } ;
	__m128 splat1 =  { 3.0f, 3.0f, 3.0f, 3.0f } ;
	__m128 splat2 =  { 1.0E20f, 1.0E20f, 1.0E20f, 1.0E20f } ;
	int start0;
	int stepouter0;
	int t;
	float *  tmp_swap_1;
	int tmpidxc0;
	__m128 u_0_0_minus_1__0_0__offs_4_0;
	__m128 u_0_0_minus_1__0_1__offs_4_0;
	__m128 u_0_0_minus_1__0_2__offs_4_1;
	__m128 u_0_0_minus_1__0_m1__offs_4_0;
	__m128 u_0_0_minus_1__m4_0__offs_0_0;
	__m128 u_0_0_minus_1__m4_1__offs_0_0;
	__m128 u_0_0_minus_1__m4_2__offs_0_1;
	__m128 u_0_0_minus_1__m4_m1__offs_0_0;
	__m128 u_0_0_plus_1__0_0__offs_0_0;
	__m128 u_0_0_plus_1__0_1__offs_0_0;
	__m128 u_0_0_plus_1__0_2__offs_0_1;
	__m128 u_0_0_plus_1__0_m1__offs_0_0;
	__m128 u_0_0_plus_1__4_0__offs_4_0;
	__m128 u_0_0_plus_1__4_1__offs_4_0;
	__m128 u_0_0_plus_1__4_2__offs_4_1;
	__m128 u_0_0_plus_1__4_m1__offs_4_0;
	int v2_blkidx_x;
	int v2_blkidx_x_idxouter;
	int v2_idx_x;
	int v2_idx_x_max;
	int v2_idx_y;
	int v2_idx_y_max;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	/*
	for t = 1..100 by 1 parallel 1 <level 0> schedule 1 { ... }
	*/
	for (t=1; t<=100; t+=1)
	{
		start0=omp_get_thread_num();
		end0=((((int)(((width+cb_x)-1)/cb_x))*((int)(((height+cb_y)-1)/cb_y)))-1);
		numthds0=omp_get_num_threads();
		stepouter0=(chunk*numthds0);
		/*
		for v2_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (v2_blkidx_x_idxouter=(start0*chunk); v2_blkidx_x_idxouter<=end0; v2_blkidx_x_idxouter+=stepouter0)
		{
			/*
			for v2_blkidx_x = v2_blkidx_x_idxouter..min(end0, ((v2_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
			*/
			for (v2_blkidx_x=v2_blkidx_x_idxouter; v2_blkidx_x<=min(end0, ((v2_blkidx_x_idxouter+chunk)-1)); v2_blkidx_x+=1)
			{
				v2_idx_y=(v2_blkidx_x/((int)(((width+cb_x)-1)/cb_x)));
				tmpidxc0=(v2_blkidx_x-(v2_idx_y*((int)(((width+cb_x)-1)/cb_x))));
				v2_idx_x=tmpidxc0;
				v2_idx_x=((v2_idx_x*cb_x)+1);
				v2_idx_x_max=min((v2_idx_x+cb_x), (width+1));
				v2_idx_y=((v2_idx_y*cb_y)+1);
				v2_idx_y_max=min((v2_idx_y+cb_y), (height+1));
				/* Index bounds calculations for iterators in v2[t=t][0] */
				/*
				for POINT p3[t=t][0] of size [1, 1] in v2[t=t][0] + [ min=[0, 0], max=[0, 0] ] parallel 1 <level 1> schedule default { ... }
				*/
				{
					/* Index bounds calculations for iterators in p3[t=t][0] */
					for (p3_idx_y=v2_idx_y; p3_idx_y<(v2_idx_y_max-1); p3_idx_y+=2)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend3=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend3; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							/* _idx21 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-1)) */
							_idx21=(_idx19+width);
							/* _idx22 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx22=((_idx19+width)+1);
							/* _idx23 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+1)) */
							_idx23=((_idx19+width)+2);
							L_unroll_1=(((u_0_0[_idx15]+u_0_0[_idx20])+(u_0_0[_idx16]+u_0_0[_idx17]))+((u_0_0[_idx19]+u_0_0[_idx21])+(u_0_0[_idx22]+u_0_0[_idx23])));
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
							u_0_1[_idx18]=(1.0f/((((u_0_0[_idx18]+L_unroll_1)-3.0f)*((L_unroll_1-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-7); p3_idx_x+=8)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							u_0_0_minus_1__0_m1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), ( * ((__m128 * )( & u_0_0[_idx3]))), 152);
							/* _idx24 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+8)) */
							_idx24=((_idx4-width)+10);
							u_0_0_plus_1__4_m1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), ( * ((__m128 * )( & u_0_0[_idx24]))), 15), 137);
							u_0_0_minus_1__0_0__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), ( * ((__m128 * )( & u_0_0[_idx5]))), 152);
							/* _idx25 = (((width+2)*p3_idx_y)+(p3_idx_x+8)) */
							_idx25=(_idx4+12);
							u_0_0_plus_1__4_0__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), ( * ((__m128 * )( & u_0_0[_idx25]))), 15), 137);
							u_0_0_minus_1__0_1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), ( * ((__m128 * )( & u_0_0[_idx8]))), 152);
							/* _idx9 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-4)) */
							_idx9=((_idx8+width)-6);
							/* _idx26 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+8)) */
							_idx26=((_idx9-width)+10);
							u_0_0_plus_1__4_1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), ( * ((__m128 * )( & u_0_0[_idx26]))), 15), 137);
							L_vec_1=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__0_m1__offs_4_0, ( * ((__m128 * )( & u_0_0[_idx3])))), _mm_add_ps(u_0_0_plus_1__4_m1__offs_4_0, u_0_0_minus_1__0_0__offs_4_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__4_0__offs_4_0, u_0_0_minus_1__0_1__offs_4_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx8]))), u_0_0_plus_1__4_1__offs_4_0)));
							/* _idx10 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx10=(_idx9+4);
							u_0_0_minus_1__m4_2__offs_0_1=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx9]))), ( * ((__m128 * )( & u_0_0[_idx10]))), 15), ( * ((__m128 * )( & u_0_0[_idx10]))), 152);
							/* _idx11 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+4)) */
							_idx11=(_idx9+8);
							u_0_0_plus_1__0_2__offs_0_1=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx10]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx10]))), ( * ((__m128 * )( & u_0_0[_idx11]))), 15), 137);
							L_vec_2=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_0__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx0])))), _mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_1__offs_0_0, u_0_0_minus_1__m4_2__offs_0_1), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx10]))), u_0_0_plus_1__0_2__offs_0_1)));
							u_0_0_minus_1__0_2__offs_4_1=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx10]))), ( * ((__m128 * )( & u_0_0[_idx11]))), 15), ( * ((__m128 * )( & u_0_0[_idx11]))), 152);
							/* _idx27 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+8)) */
							_idx27=(_idx9+12);
							u_0_0_plus_1__4_2__offs_4_1=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx11]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx11]))), ( * ((__m128 * )( & u_0_0[_idx27]))), 15), 137);
							L_vec_3=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__0_0__offs_4_0, ( * ((__m128 * )( & u_0_0[_idx5])))), _mm_add_ps(u_0_0_plus_1__4_0__offs_4_0, u_0_0_minus_1__0_1__offs_4_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__4_1__offs_4_0, u_0_0_minus_1__0_2__offs_4_1), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx11]))), u_0_0_plus_1__4_2__offs_4_1)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx5])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx5]))), L_vec_1), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_1, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx7])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), L_vec_2), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_2, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx8])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx8]))), L_vec_3), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_3, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							/* _idx21 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-1)) */
							_idx21=(_idx19+width);
							/* _idx22 = (((width+2)*(p3_idx_y+2))+p3_idx_x) */
							_idx22=((_idx19+width)+1);
							/* _idx23 = (((width+2)*(p3_idx_y+2))+(p3_idx_x+1)) */
							_idx23=((_idx19+width)+2);
							L_unroll_1=(((u_0_0[_idx15]+u_0_0[_idx20])+(u_0_0[_idx16]+u_0_0[_idx17]))+((u_0_0[_idx19]+u_0_0[_idx21])+(u_0_0[_idx22]+u_0_0[_idx23])));
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
							u_0_1[_idx18]=(1.0f/((((u_0_0[_idx18]+L_unroll_1)-3.0f)*((L_unroll_1-3.0f)*1.0E20f))+1.0f));
						}
					}
					for (; p3_idx_y<v2_idx_y_max; p3_idx_y+=1)
					{
						p3_idx_x=v2_idx_x;
						/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
						_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
						prologueend4=min((v2_idx_x+((16-((((uintptr_t)( & u_0_1[_idx0]))+((uintptr_t)15))&15))/sizeof (float))), v2_idx_x_max);
						for (p3_idx_x=v2_idx_x; p3_idx_x<prologueend4; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
						for (; p3_idx_x<(v2_idx_x_max-7); p3_idx_x+=8)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx0=(((width+2)*p3_idx_y)+p3_idx_x);
							/* _idx1 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-4)) */
							_idx1=((_idx0-width)-6);
							/* _idx2 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx2=(_idx1+4);
							u_0_0_minus_1__m4_m1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx1]))), ( * ((__m128 * )( & u_0_0[_idx2]))), 15), ( * ((__m128 * )( & u_0_0[_idx2]))), 152);
							/* _idx3 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+4)) */
							_idx3=(_idx1+8);
							u_0_0_plus_1__0_m1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), 137);
							/* _idx4 = (((width+2)*p3_idx_y)+(p3_idx_x-4)) */
							_idx4=((_idx1+width)+2);
							u_0_0_minus_1__m4_0__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx4]))), ( * ((__m128 * )( & u_0_0[_idx0]))), 15), ( * ((__m128 * )( & u_0_0[_idx0]))), 152);
							/* _idx5 = (((width+2)*p3_idx_y)+(p3_idx_x+4)) */
							_idx5=((_idx1+width)+10);
							u_0_0_plus_1__0_0__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), 137);
							/* _idx6 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-4)) */
							_idx6=((_idx4+width)+2);
							/* _idx7 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx7=((_idx4+width)+6);
							u_0_0_minus_1__m4_1__offs_0_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx6]))), ( * ((__m128 * )( & u_0_0[_idx7]))), 15), ( * ((__m128 * )( & u_0_0[_idx7]))), 152);
							/* _idx8 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+4)) */
							_idx8=((_idx4+width)+10);
							u_0_0_plus_1__0_1__offs_0_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), 137);
							L_vec_0=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__m4_m1__offs_0_0, ( * ((__m128 * )( & u_0_0[_idx2])))), _mm_add_ps(u_0_0_plus_1__0_m1__offs_0_0, u_0_0_minus_1__m4_0__offs_0_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__0_0__offs_0_0, u_0_0_minus_1__m4_1__offs_0_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx7]))), u_0_0_plus_1__0_1__offs_0_0)));
							u_0_0_minus_1__0_m1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx2]))), ( * ((__m128 * )( & u_0_0[_idx3]))), 15), ( * ((__m128 * )( & u_0_0[_idx3]))), 152);
							/* _idx24 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+8)) */
							_idx24=((_idx4-width)+10);
							u_0_0_plus_1__4_m1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx3]))), ( * ((__m128 * )( & u_0_0[_idx24]))), 15), 137);
							u_0_0_minus_1__0_0__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx0]))), ( * ((__m128 * )( & u_0_0[_idx5]))), 15), ( * ((__m128 * )( & u_0_0[_idx5]))), 152);
							/* _idx25 = (((width+2)*p3_idx_y)+(p3_idx_x+8)) */
							_idx25=(_idx4+12);
							u_0_0_plus_1__4_0__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx5]))), ( * ((__m128 * )( & u_0_0[_idx25]))), 15), 137);
							u_0_0_minus_1__0_1__offs_4_0=_mm_shuffle_ps(_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx7]))), ( * ((__m128 * )( & u_0_0[_idx8]))), 15), ( * ((__m128 * )( & u_0_0[_idx8]))), 152);
							/* _idx9 = (((width+2)*(p3_idx_y+2))+(p3_idx_x-4)) */
							_idx9=((_idx8+width)-6);
							/* _idx26 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+8)) */
							_idx26=((_idx9-width)+10);
							u_0_0_plus_1__4_1__offs_4_0=_mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), _mm_shuffle_ps(( * ((__m128 * )( & u_0_0[_idx8]))), ( * ((__m128 * )( & u_0_0[_idx26]))), 15), 137);
							L_vec_1=_mm_add_ps(_mm_add_ps(_mm_add_ps(u_0_0_minus_1__0_m1__offs_4_0, ( * ((__m128 * )( & u_0_0[_idx3])))), _mm_add_ps(u_0_0_plus_1__4_m1__offs_4_0, u_0_0_minus_1__0_0__offs_4_0)), _mm_add_ps(_mm_add_ps(u_0_0_plus_1__4_0__offs_4_0, u_0_0_minus_1__0_1__offs_4_0), _mm_add_ps(( * ((__m128 * )( & u_0_0[_idx8]))), u_0_0_plus_1__4_1__offs_4_0)));
							( * ((__m128 * )( & u_0_1[_idx0])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx0]))), L_vec_0), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_0, splat1), splat2)), splat0));
							( * ((__m128 * )( & u_0_1[_idx5])))=_mm_div_ps(splat0, _mm_add_ps(_mm_mul_ps(_mm_sub_ps(_mm_add_ps(( * ((__m128 * )( & u_0_0[_idx5]))), L_vec_1), splat1), _mm_mul_ps(_mm_sub_ps(L_vec_1, splat1), splat2)), splat0));
						}
						for (; p3_idx_x<v2_idx_x_max; p3_idx_x ++ )
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx12 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx12=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							/* _idx13 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx13=(_idx12+1);
							/* _idx14 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx14=(_idx13+1);
							/* _idx15 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx15=((_idx13+width)+1);
							/* _idx16 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx16=(_idx15+2);
							/* _idx17 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx17=((_idx15+width)+2);
							/* _idx18 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx18=((_idx15+width)+3);
							/* _idx19 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx19=((_idx15+width)+4);
							L=(((u_0_0[_idx12]+u_0_0[_idx13])+(u_0_0[_idx14]+u_0_0[_idx15]))+((u_0_0[_idx16]+u_0_0[_idx17])+(u_0_0[_idx18]+u_0_0[_idx19])));
							/* _idx20 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx20=(_idx15+1);
							u_0_1[_idx20]=(1.0f/((((u_0_0[_idx20]+L)-3.0f)*((L-3.0f)*1.0E20f))+1.0f));
						}
					}
				}
			}
		}
#pragma omp barrier 
		( * u_0_1_out)=u_0_1;
		tmp_swap_1=u_0_0;
		u_0_0=u_0_1;
		u_0_1=tmp_swap_1;
	}
}

static void (* g_rgCodeVariants0[])(float *  *  , float *  , float *  , int , int , int , int , int ) =  { game_of_life___unroll_p3_102, game_of_life___unroll_p3_201, game_of_life___unroll_p3_101, game_of_life___unroll_p3_202 } ;
/*
(L[0][0]=(((u[-1][-1][0][0]+u[0][-1][0][0])+(u[1][-1][0][0]+u[-1][0][0][0]))+((u[1][0][0][0]+u[-1][1][0][0])+(u[0][1][0][0]+u[1][1][0][0]))))
(u[0][0][1][0]=(1.0/((((u[0][0][0][0]+L)-3.0)*((L-3.0)*1.0E20))+1.0)))

*/
void game_of_life(float *  *  u_0_1_out, float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk, int _unroll_p3)
{
	g_rgCodeVariants0[_unroll_p3](u_0_1_out, u_0_0, u_0_1, width, height, cb_x, cb_y, chunk);
}

void initialize_game_of_life(float *  u_0_0, float *  u_0_1, int width, int height, int cb_x, int cb_y, int chunk)
{
	float L;
	int _idx0;
	int _idx1;
	int _idx2;
	int _idx3;
	int _idx4;
	int _idx5;
	int _idx6;
	int _idx7;
	int _idx8;
	int end0;
	int numthds0;
	int p3_idx_x;
	int p3_idx_y;
	int start0;
	int stepouter0;
	int t;
	float *  tmp_swap_0;
	int tmpidxc0;
	int tmpidxc1;
	int v2_blkidx_x;
	int v2_blkidx_x_idxouter;
	int v2_blkidx_y;
	int v2_idx_x;
	int v2_idx_x_max;
	int v2_idx_y;
	int v2_idx_y_max;
	/*
	Initializations
	*/
	/*
	Implementation
	*/
	/*
	for t = 1..100 by 1 parallel 1 <level 0> schedule 1 { ... }
	*/
	for (t=1; t<=100; t+=1)
	{
		start0=omp_get_thread_num();
		end0=((((int)(((width+cb_x)-1)/cb_x))*((int)(((height+cb_y)-1)/cb_y)))-1);
		numthds0=omp_get_num_threads();
		stepouter0=(chunk*numthds0);
		/*
		for v2_blkidx_x_idxouter = (start0*chunk)..end0 by stepouter0 parallel 1 <level 1> schedule 1 { ... }
		*/
		for (v2_blkidx_x_idxouter=(start0*chunk); v2_blkidx_x_idxouter<=end0; v2_blkidx_x_idxouter+=stepouter0)
		{
			/*
			for v2_blkidx_x = v2_blkidx_x_idxouter..min(end0, ((v2_blkidx_x_idxouter+chunk)-1)) by 1 parallel 1 <level 1> schedule 1 { ... }
			*/
			for (v2_blkidx_x=v2_blkidx_x_idxouter; v2_blkidx_x<=min(end0, ((v2_blkidx_x_idxouter+chunk)-1)); v2_blkidx_x+=1)
			{
				v2_idx_y=(v2_blkidx_x/((int)(((width+cb_x)-1)/cb_x)));
				tmpidxc1=(v2_blkidx_x-(v2_idx_y*((int)(((width+cb_x)-1)/cb_x))));
				v2_idx_x=tmpidxc1;
				v2_idx_x=((v2_idx_x*cb_x)+1);
				v2_idx_x_max=min((v2_idx_x+cb_x), (width+1));
				v2_idx_y=((v2_idx_y*cb_y)+1);
				v2_idx_y_max=min((v2_idx_y+cb_y), (height+1));
				/* Index bounds calculations for iterators in v2[t=t][0] */
				/*
				for POINT p3[t=t][0] of size [1, 1] in v2[t=t][0] + [ min=[0, 0], max=[0, 0] ] parallel 1 <level 1> schedule default { ... }
				*/
				{
					/* Index bounds calculations for iterators in p3[t=t][0] */
					for (p3_idx_y=v2_idx_y; p3_idx_y<v2_idx_y_max; p3_idx_y+=1)
					{
						for (p3_idx_x=v2_idx_x; p3_idx_x<v2_idx_x_max; p3_idx_x+=1)
						{
							/* Index bounds calculations for iterators in p3[t=t][0] */
							/*
							p3[t=(t+1)][0]=stencil(p3[t=t][0])
							*/
							/* _idx0 = (((width+2)*(p3_idx_y-1))+(p3_idx_x-1)) */
							_idx0=(((width+2)*(p3_idx_y-1))+(p3_idx_x-1));
							u_0_0[_idx0]=((1.0+((p3_idx_x+-1)*0.1))+((p3_idx_y+-1)*0.01));
							/* _idx1 = (((width+2)*p3_idx_y)+(p3_idx_x-1)) */
							_idx1=((_idx0+width)+2);
							u_0_0[_idx1]=((1.0+((p3_idx_x+-1)*0.1))+(p3_idx_y*0.01));
							/* _idx2 = (((width+2)*(p3_idx_y+1))+(p3_idx_x-1)) */
							_idx2=((_idx1+width)+2);
							u_0_0[_idx2]=((1.0+((p3_idx_x+-1)*0.1))+((p3_idx_y+1)*0.01));
							/* _idx3 = (((width+2)*(p3_idx_y-1))+p3_idx_x) */
							_idx3=(_idx0+1);
							u_0_0[_idx3]=((1.0+(p3_idx_x*0.1))+((p3_idx_y+-1)*0.01));
							/* _idx4 = (((width+2)*(p3_idx_y+1))+p3_idx_x) */
							_idx4=((_idx1+width)+3);
							u_0_0[_idx4]=((1.0+(p3_idx_x*0.1))+((p3_idx_y+1)*0.01));
							/* _idx5 = (((width+2)*(p3_idx_y-1))+(p3_idx_x+1)) */
							_idx5=(_idx1-width);
							u_0_0[_idx5]=((1.0+((p3_idx_x+1)*0.1))+((p3_idx_y+-1)*0.01));
							/* _idx6 = (((width+2)*p3_idx_y)+(p3_idx_x+1)) */
							_idx6=(_idx1+2);
							u_0_0[_idx6]=((1.0+((p3_idx_x+1)*0.1))+(p3_idx_y*0.01));
							/* _idx7 = (((width+2)*(p3_idx_y+1))+(p3_idx_x+1)) */
							_idx7=((_idx1+width)+4);
							u_0_0[_idx7]=((1.0+((p3_idx_x+1)*0.1))+((p3_idx_y+1)*0.01));
							L=1.0;
							/* _idx8 = (((width+2)*p3_idx_y)+p3_idx_x) */
							_idx8=(_idx1+1);
							u_0_0[_idx8]=((1.0+(p3_idx_x*0.1))+(p3_idx_y*0.01));
							u_0_1[_idx8]=((11.0+(p3_idx_x*0.1))+(p3_idx_y*0.01));
						}
					}
				}
			}
		}
#pragma omp barrier 
	}
}

