/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_unibas_cs_hpwc_patus_ilp_ILPModel_EOperator */

#ifndef _Included_ch_unibas_cs_hpwc_patus_ilp_ILPModel_EOperator
#define _Included_ch_unibas_cs_hpwc_patus_ilp_ILPModel_EOperator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
