/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_unibas_cs_hpwc_patus_ilp_ILPSolver */

#ifndef _Included_ch_unibas_cs_hpwc_patus_ilp_ILPSolver
#define _Included_ch_unibas_cs_hpwc_patus_ilp_ILPSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_unibas_cs_hpwc_patus_ilp_ILPSolver
 * Method:    solveInternal
 * Signature: (Lch/unibas/cs/hpwc/patus/ilp/ILPModel;[D[DI)I
 */
JNIEXPORT jint JNICALL Java_ch_unibas_cs_hpwc_patus_ilp_ILPSolver_solveInternal
  (JNIEnv *, jobject, jobject, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
